### ISSUE TITLE
1.9 tag still not found

### ISSUE THREAD

**Issue by netmarkjp** [tcnksm/dockerfile-gox#9]
On https://hub.docker.com/r/tcnksm/gox/tags/ , 
README was updated but 1.9 tag still not found 😢

**Comment by tcnksm** [comment]
Sorry for late. Pushed image.

**Comment by netmarkjp** [comment]
Thanks a lot ☺️ 

----

FYI: `latest` looks still `1.7` .

![image](https://user-images.githubusercontent.com/87943/36140833-05743aac-10e6-11e8-8057-b99730628a2f.png)
